package com.solartracker.service.impl;
import com.solartracker.service.ConsumerService;
import com.solartracker.dto.request.ConsumerRequest; import com.solartracker.dto.response.ConsumerResponse; import com.solartracker.entity.Consumer; import com.solartracker.exception.DuplicateResourceException; import com.solartracker.exception.ResourceNotFoundException; import com.solartracker.repository.ConsumerRepository; import lombok.RequiredArgsConstructor; import org.springframework.data.jpa.domain.Specification; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @RequiredArgsConstructor
public class ConsumerServiceImpl implements ConsumerService {
 private final ConsumerRepository repo;
 @Override @Transactional(readOnly=true) public java.util.List<ConsumerResponse> list(String search){ Specification<Consumer> s=(root,q,cb)->{ if(search==null||search.isBlank()) return null; String x="%"+search.toLowerCase()+"%"; return cb.or(cb.like(cb.lower(root.get("consumerNumber")),x),cb.like(cb.lower(root.get("name")),x),cb.like(cb.lower(root.get("mobile")),x),cb.like(cb.lower(root.get("district")),x));}; return repo.findAll(s).stream().map(this::to).toList(); }
 @Override @Transactional(readOnly=true) public ConsumerResponse get(Long id){return to(find(id));}
 @Override @Transactional(readOnly=true) public ConsumerResponse byNumber(String n){return to(repo.findByConsumerNumber(n).orElseThrow(()->new ResourceNotFoundException("Consumer not found: "+n,"CONSUMER_NOT_FOUND")));}
 @Override @Transactional public ConsumerResponse create(ConsumerRequest r){if(repo.existsByConsumerNumber(r.getConsumerNumber())) throw new DuplicateResourceException("Consumer number already exists: "+r.getConsumerNumber()); Consumer c=new Consumer(); apply(c,r); return to(repo.save(c));}
 @Override @Transactional public ConsumerResponse update(Long id,ConsumerRequest r){Consumer c=find(id); if(repo.existsByConsumerNumberAndIdNot(r.getConsumerNumber(),id)) throw new DuplicateResourceException("Consumer number already exists: "+r.getConsumerNumber()); apply(c,r); return to(repo.save(c));}
 @Override @Transactional public void delete(Long id){repo.delete(find(id));}
 private Consumer find(Long id){return repo.findById(id).orElseThrow(()->new ResourceNotFoundException("Consumer not found: "+id,"CONSUMER_NOT_FOUND"));}
 private void apply(Consumer c,ConsumerRequest r){c.setConsumerNumber(r.getConsumerNumber());c.setUlaApplicationId(r.getUlaApplicationId());c.setName(r.getName());c.setMobile(r.getMobile());c.setAlternateMobile(r.getAlternateMobile());c.setAddress(r.getAddress());c.setVillage(r.getVillage());c.setMandal(r.getMandal());c.setDistrict(r.getDistrict());c.setState(r.getState());c.setPincode(r.getPincode());c.setSection(r.getSection());c.setDistribution(r.getDistribution());c.setSiteType(r.getSiteType());if(r.getStatus()!=null)c.setStatus(r.getStatus());}
 private ConsumerResponse to(Consumer c){return ConsumerResponse.builder().id(c.getId()).consumerNumber(c.getConsumerNumber()).ulaApplicationId(c.getUlaApplicationId()).name(c.getName()).mobile(c.getMobile()).alternateMobile(c.getAlternateMobile()).address(c.getAddress()).village(c.getVillage()).mandal(c.getMandal()).district(c.getDistrict()).state(c.getState()).pincode(c.getPincode()).section(c.getSection()).distribution(c.getDistribution()).siteType(c.getSiteType()).status(c.getStatus()).createdAt(c.getCreatedAt()).updatedAt(c.getUpdatedAt()).build();}
}
