import { Injectable, inject } from '@angular/core';
import { HttpClient, HttpParams } from '@angular/common/http';
import { Observable } from 'rxjs';
export interface Consumer {id:number;consumerNumber:string;ulaApplicationId?:string;name:string;mobile?:string;alternateMobile?:string;address?:string;village?:string;mandal?:string;district?:string;state?:string;pincode?:string;section?:string;distribution?:string;siteType?:string;status?:string;}
export interface Installation {id:number;consumerId?:number;consumerNumber?:string;ulaApplicationId:string;section?:string;distribution?:string;serviceNumber:string;consumerName:string;consumerMobile?:string;newMobile?:string;inverterSerialNumber?:string;siteType?:string;remarks?:string;dcrStatus:string;status:string;assignedInstaller?:{id:number;username:string;fullName?:string};panelSerialNumbers:string[];createdAt:string;}
@Injectable({providedIn:'root'}) export class ApiService { private http=inject(HttpClient); private base='/api';
 login(body:any){return this.http.post<any>(`${this.base}/auth/login`,body)} me(){return this.http.get<any>(`${this.base}/auth/me`)}
 consumers(search=''){let p=new HttpParams();if(search)p=p.set('search',search);return this.http.get<Consumer[]>(`${this.base}/consumers`,{params:p})} consumerByNumber(n:string){return this.http.get<Consumer>(`${this.base}/consumers/by-number/${encodeURIComponent(n)}`)} createConsumer(b:any){return this.http.post<Consumer>(`${this.base}/consumers`,b)}
 installations(params:any={}){let p=new HttpParams().set('page',params.page??0).set('size',params.size??20);Object.keys(params).filter(k=>params[k]!==undefined&&params[k]!==''&&k!=='page'&&k!=='size').forEach(k=>p=p.set(k,String(params[k])));return this.http.get<any>(`${this.base}/installations`,{params:p})} installation(id:number){return this.http.get<Installation>(`${this.base}/installations/${id}`)} createInstallation(b:any){return this.http.post<Installation>(`${this.base}/installations`,b)} updateDcrStatus(id:number,b:any){return this.http.patch<Installation>(`${this.base}/installations/${id}/dcr-status`,b)}
 panels(id:number){return this.http.get<any[]>(`${this.base}/installations/${id}/panels`)} addPanel(id:number,b:any){return this.http.post<any>(`${this.base}/installations/${id}/panels`,b)} deletePanel(id:number,pid:number){return this.http.delete(`${this.base}/installations/${id}/panels/${pid}`)}
 inverter(id:number){return this.http.get<any>(`${this.base}/installations/${id}/inverter`)} addInverter(id:number,b:any){return this.http.post<any>(`${this.base}/installations/${id}/inverter`,b)}
 verify(id:number,b:any){return this.http.post<any>(`${this.base}/installations/${id}/verification`,b)} location(id:number){return this.http.get<any>(`${this.base}/installations/${id}/location`)} saveLocation(id:number,b:any){return this.http.post<any>(`${this.base}/installations/${id}/location`,b)}
 photos(id:number){return this.http.get<any[]>(`${this.base}/installations/${id}/photos`)} uploadPhoto(id:number,form:FormData){return this.http.post<any>(`${this.base}/installations/${id}/photos`,form)} review(id:number){return this.http.get<any>(`${this.base}/installations/${id}/review`)} submit(id:number,b:any={}){return this.http.post<any>(`${this.base}/installations/${id}/submit`,b)}
 dcr(id:number){return this.http.get<any>(`${this.base}/installations/${id}/dcr`)} saveDcr(id:number,b:any){return this.http.post<any>(`${this.base}/installations/${id}/dcr`,b)}
}
