spring.application.name=solar-tracker-backend
server.port=${SERVER_PORT:8081}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}

spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jackson.default-property-inclusion=non_null

app.jwt.secret=${JWT_SECRET:dev-only-secret-key-change-me-please-32bytes-min}
app.jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

logging.level.com.solartracker=DEBUG
logging.level.org.springframework.security=INFO
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=20MB
